[versions]
# https://mvnrepository.com/artifact/org.mapstruct/mapstruct
org-mapstruct = "1.6.3"
# https://mvnrepository.com/artifact/com.google.guava/guava
com-google-guava = "33.5.0-jre"
# https://mvnrepository.com/artifact/org.imgscalr/imgscalr-lib
org-imgscalr-imgscalr-lib = "4.2"
# https://mvnrepository.com/artifact/com.google.code.gson/gson
com-google-code-gson = "2.13.2"

[libraries]
org-mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "org-mapstruct" }
org-mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "org-mapstruct" }

com-google-guava = { module = "com.google.guava:guava", version.ref = "com-google-guava" }

org-imgscalr-imgscalr-lib = { module = "org.imgscalr:imgscalr-lib", version.ref = "org-imgscalr-imgscalr-lib" }

com-google-code-gson = { module = "com.google.code.gson:gson", version.ref = "com-google-code-gson" }
